@host = http://localhost:3333/transactions

### Criando uma transação
POST {{host}}
Content-Type: application/json

{
  "title": "Teste Salario",
  "value": 5000,
  "type": "income",
  "category": "Others"
}

### GET
GET {{host}}

### DELETE
DELETE {{host}}/b0191d9a-f9bf-4127-b5e2-2afe0585c066

### Send Multiform Data
@formDataLimit = XXXXXXXXXXXXXXXXXXXXXXXX

POST {{host}}/import/
Content-Type: multipart/form-data; boundary={{formDataLimit}}

--{{formDataLimit}}
Content-Disposition: form-data; name="file"; filename="transactions.csv"
Content-Type: text/csv

< ./../src/__tests__/import_template.csv
--{{formDataLimit}}--
